# this is a template
# kubectl apply -f secret.yaml -n ai-python-demo
apiVersion: v1
kind: Secret
metadata:
  name: ai-python-demo-secret
  namespace: ai-python-demo
type: Opaque
stringData:
  POSTGRES_DB: ${DB_NAME}
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASS}
  SECRET_KEY: ${APP_KEY}
  DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}