apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-logs-pvc
  namespace: ai-python-demo
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
