"""Initial migration

Revision ID: 1f257cdcff5c
Revises: 759d5188a40e
Create Date: 2026-05-23 03:52:23.683457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f257cdcff5c'
down_revision = '759d5188a40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('favorite_tags_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('follows_follower_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('follows_following_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['following_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_recipient_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_tags_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('replies_parent_reply_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['parent_reply_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saved_posts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saved_posts_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_posts_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('saved_posts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('replies_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('replies_author_id_fkey'), 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('replies_parent_reply_id_fkey'), 'replies', ['parent_reply_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_author_id_fkey'), 'users', ['author_id'], ['id'])

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_tags_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('post_tags_tag_id_fkey'), 'tags', ['tag_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_recipient_id_fkey'), 'users', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('follows_following_id_fkey'), 'users', ['following_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('follows_follower_id_fkey'), 'users', ['follower_id'], ['id'])

    with op.batch_alter_table('favorite_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_tags_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('favorite_tags_tag_id_fkey'), 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###
