"""Initial migration

Revision ID: c62f9aee6afc
Revises: 
Create Date: 2026-03-26 19:08:02.503424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62f9aee6afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('favorite_tags_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('favorite_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('follows_following_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('follows_follower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['following_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_created_at'))
        batch_op.drop_index(batch_op.f('idx_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('idx_messages_sender_id'))
        batch_op.create_index(batch_op.f('ix_blog_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_recipient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_tags_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_posts_author_id'))
        batch_op.drop_index(batch_op.f('idx_posts_created_at'))
        batch_op.drop_index(batch_op.f('idx_posts_status'))
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('posts_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_replies_author_id'))
        batch_op.drop_index(batch_op.f('idx_replies_parent_reply_id'))
        batch_op.drop_index(batch_op.f('idx_replies_post_id'))
        batch_op.create_index(batch_op.f('ix_blog_replies_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_replies_parent_reply_id'), ['parent_reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_replies_post_id'), ['post_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('replies_parent_reply_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['parent_reply_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('saved_posts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saved_posts_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='blog')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], referent_schema='blog')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tags_name'))
        batch_op.drop_constraint(batch_op.f('tags_name_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_blog_tags_name'), ['name'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_blog_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_users_username'))
        batch_op.drop_index(batch_op.f('ix_blog_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_tags_name'))
        batch_op.create_unique_constraint(batch_op.f('tags_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_tags_name'), ['name'], unique=False)

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_posts_post_id_fkey'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('saved_posts_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('replies_author_id_fkey'), 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('replies_post_id_fkey'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('replies_parent_reply_id_fkey'), 'replies', ['parent_reply_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_blog_replies_post_id'))
        batch_op.drop_index(batch_op.f('ix_blog_replies_parent_reply_id'))
        batch_op.drop_index(batch_op.f('ix_blog_replies_author_id'))
        batch_op.create_index(batch_op.f('idx_replies_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_replies_parent_reply_id'), ['parent_reply_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_replies_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_author_id_fkey'), 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_blog_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))
        batch_op.create_index(batch_op.f('idx_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_tags_post_id_fkey'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('post_tags_tag_id_fkey'), 'tags', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('messages_recipient_id_fkey'), 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_blog_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_blog_messages_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_blog_messages_created_at'))
        batch_op.create_index(batch_op.f('idx_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_messages_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('follows_follower_id_fkey'), 'users', ['follower_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('follows_following_id_fkey'), 'users', ['following_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('favorite_tags_tag_id_fkey'), 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('favorite_tags_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
